### ISSUE TITLE
Getting HTTP Error 404: Not Found when downloading dependencies from http://repo.minecraft-vr.com/

### ISSUE THREAD

**Issue by virtuoushub** [mabrowning/minecrift#136]
[update]
[related](https://github.com/blog/1925-github-pages-legacy-ip-brownout)

Steps to reproduce:

1. Go to http://repo.minecraft-vr.com/

Observerd result:

* Page displaying: "Site temporarily disabled"

I ran into this issue while running the [install script](https://github.com/virtuoushub/minecrift/blob/port_to_1_8_0/install.sh):

`$ sh install.sh`

It is preventing me from downloading some dependencies:

```
Downloading: JRiftLibrary-0.4.2.1-natives-osx.jar
HTTP Error 404: Not Found
Download of /PATH_TO_DIRECTORY_HOLDING_REPO/minecrift/mcp910-pre1/jars/libraries/de/fruitfly/ovr/JRiftLibrary/0.4.2.1/JRiftLibrary-0.4.2.1-natives-osx.jar failed, download it manually from 'http://repo.minecraft-vr.com/de/fruitfly/ovr/JRiftLibrary/0.4.2.1/JRiftLibrary-0.4.2.1-natives-osx.jar' to '/PATH_TO_DIRECTORY_HOLDING_REPO/minecrift/mcp910-pre1/jars/libraries/de/fruitfly/ovr/JRiftLibrary/0.4.2.1/JRiftLibrary-0.4.2.1-natives-osx.jar'
ERROR: File is not a zip file
Traceback (most recent call last):
  File "install.py", line 356, in <module>
    main(os.path.abspath(mcp_version))
  File "install.py", line 308, in main
    download_deps( mcp_dir )
  File "install.py", line 216, in download_deps
    extractnatives( lib, jars, file, flat_native_dir )
  File "install.py", line 236, in extractnatives
    zip = zipfile.ZipFile(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
```

**Comment by virtuoushub** [comment]
No longer seeing a page displaying: "Site temporarily disabled" when visiting http://repo.minecraft-vr.com/ and ```sh install.sh``` no longer has `... HTTP Error 404: Not Found ...`
