### ISSUE TITLE
Crash on Start (OS X)

### ISSUE THREAD

**Issue by JonasFranzDEV** [mabrowning/minecrift#156]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 21.07.15 16:48
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at bao.setupRenderConfiguration(Minecraft.java:3795)
	at bao.ak(Minecraft.java:1328)
	at bao.f(Minecraft.java:1271)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10.3
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 114388488 bytes (109 MB) / 150695936 bytes (143 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 5 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: minecrift-1.7.10-R1c-nohydra
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce GT 750M OpenGL Engine GL version 2.1 NVIDIA-10.2.7 310.41.25f01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by StellaArtois** [comment]
Make sure the Oculus runtime is installed. I decent error needs to be thrown here ideally though!

**Comment by webdevbrian** [comment]
Same issue, Oculus runtime .7 is installed.

**Comment by StellaArtois** [comment]
.7 support is in progress. When done I'll try to add a check for supported runtimes on startup.

**Comment by webdevbrian** [comment]
Awesome! Thanks Stella. Can't wait! You have a donation link right?
