### ISSUE TITLE
Game cannot detect Oculus Rift (DK2 / newest runtime)

### ISSUE THREAD

**Issue by jennybrown8** [mabrowning/minecrift#158]
I'm working with the 1.7 Minecrift without Forge.  It's reporting that it can't find an attached Rift, even though my demo scene through the rift software works fine.  I'm on a DK2.  I was seeing the issue with my prior runtime (from months ago) and today updated to the Rift 0.7.0.0 runtime just in case that would fix it (it didn't).  The error I'm seeing both before and after the runtime upgrade is:

```
java.lang.NullPointerException: Unexpected error
	at bao.setupRenderConfiguration(Minecraft.java:3795)
	at bao.ak(Minecraft.java:1328)
	at bao.f(Minecraft.java:1271)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 310718928 bytes (296 MB) / 957718528 bytes (913 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: minecrift-1.7.10-R1c-nohydra
	LWJGL: 2.9.1
	OpenGL: GeForce GT 750M/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [Better18.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\jenny\AppData\Roaming\.minecraft\crash-reports\crash-2015-10-11_13.23.47-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
No Oculus Rift devices found, creating dummy DK1 device...
Unable to create Oculus Rift device interface.
No Oculus Rift devices found, creating dummy DK1 device...
Unable to create Oculus Rift device interface.
No Oculus Rift devices found, creating dummy DK1 device...
Unable to create Oculus Rift device interface.
No Oculus Rift devices found, creating dummy DK1 device...
Unable to create Oculus Rift device interface.
No Oculus Rift devices found, creating dummy DK1 device...
Unable to create Oculus Rift device interface.
No Oculus Rift devices found, creating dummy DK1 device...
Unable to create Oculus Rift device interface.
No Oculus Rift devices found, creating dummy DK1 device...
Unable to create Oculus Rift device interface.
No Oculus Rift devices found, creating dummy DK1 device...
Unable to create Oculus Rift device interface.
No Oculus Rift devices found, creating dummy DK1 device...
Unable to create Oculus Rift device interface.
No Oculus Rift devices found, creating dummy DK1 device...
Unable to create Oculus Rift device interface.
```

**Comment by StellaArtois** [comment]
We currently support the 0.5 runtime. 0.7 support is in progress.

**Comment by jennybrown8** [comment]
Thanks, I'll see if I can still download 0.5.

**Comment by StellaArtois** [comment]
One of the aim with the 0.7 support is to give a better error if an
incompatible runtime is detected. The current error isn't very helpful!

**Comment by jennybrown8** [comment]
0.5 is working! Yeah!!  Thanks so much.  And yeah, better error messages would be awesome.
