### ISSUE TITLE
Compiling issue w/ port_to_1_8_8

### ISSUE THREAD

**Issue by Wolfos360** [mabrowning/minecrift#160]
Trying to install.sh/build.sh fails. This error is what I'm getting thrown when applying Optifine. I'm likely doing something wrong I'm sure but..

Traceback (most recent call last):
  File "C:\minecrift-public-188\install.py", line 653, in <module>
    main(os.path.abspath(mcp_version))
  File "C:\minecrift-public-188\install.py", line 477, in main
    zipmerge( minecraft_jar, optifine )
  File "C:\minecrift-public-188\install.py", line 373, in zipmerge
    source = zipfile.ZipFile( source_file, 'r' )
  File "C:\Python27\lib\zipfile.py", line 684, in __init__
    self._GetContents()
  File "C:\Python27\lib\zipfile.py", line 710, in _GetContents
    self._RealGetContents()
  File "C:\Python27\lib\zipfile.py", line 722, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file

Not super experienced with compiling in general, likely doing something wrong. Help appreciated :+1:

**Comment by StellaArtois** [comment]
This branch is a WIP currently, so it all isn’t going to work anyway at the moment! 

That said, the Optifine download should be working, unless the url has changed or the download has been pulled.

**Comment by Wolfos360** [comment]
Ah okay. Are any of the branches working with runtime .7 .8 yet? I assumed port_to_oculus_0.9 doesn't work either ;w;

**Comment by StellaArtois** [comment]
Port to 0.9 is a Wip as well, but it should be in a state whereby you can run it up with 0.8...

**Comment by Wolfos360** [comment]
Aight now I GOTTA Be doing something wrong. When trying to run it through Eclipse I get this.

Exception in thread "main" java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at org.lwjgl.Sys$1.run(Sys.java:73)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:95)
	at org.lwjgl.Sys.<clinit>(Sys.java:112)
	at net.minecraft.client.Minecraft.getSystemTime(Minecraft.java:2900)
	at net.minecraft.client.main.Main.main(Main.java:76)
	at Start.main(Start.java:91)

Thoughts? : O

**Comment by StellaArtois** [comment]
Use the intelij project :D

I'll update the scripts to produce a working eclipse project at some point. Currently I think the eclipse project is just whatever has been generated by MCP, but not sure. I haven't touched it tbh.

**Comment by Wolfos360** [comment]
...I am so sorry to keep bugging you like this ;w;

Error:(19, 8) java: com.mtbs3d.minecrift.provider.MCOculus is not abstract and does not override abstract method setCurrentSwapTextureIndex(int) in com.mtbs3d.minecrift.api.IStereoProvider
Error:(128, 9) java: cannot find symbol
  symbol:   method submitFrame()
  location: class com.mtbs3d.minecrift.provider.MCOculus
Error:(394, 43) java: incompatible types: possible lossy conversion from long to int

This pops up when trying to run it with IntelliJ....

**Comment by StellaArtois** [comment]
Sounds like you need to do a
git submodule update --recursive 
or similar?

**Comment by Wolfos360** [comment]
Okay so... I re downloaded Jrift and tried just... re adding it instead. Now this comes up..

C:\minecrift-public-rift\mcp908\src\minecraft\com\mtbs3d\minecrift\provider\MCOculus.java
Error:(59, 12) java: cannot find symbol
  symbol:   class SwapTextureSet
  location: class com.mtbs3d.minecrift.provider.MCOculus
C:\minecrift-public-rift\mcp908\src\minecraft\com\mtbs3d\minecrift\api\IStereoProvider.java
Error:(39, 12) java: cannot find symbol
  symbol:   class SwapTextureSet
  location: interface com.mtbs3d.minecrift.api.IStereoProvider
C:\minecrift-public-rift\mcp908\src\minecraft\com\mtbs3d\minecrift\provider\NullStereoRenderer.java
Error:(176, 12) java: cannot find symbol
  symbol:   class SwapTextureSet
  location: class com.mtbs3d.minecrift.provider.NullStereoRenderer
C:\minecrift-public-rift\mcp908\src\minecraft\net\minecraft\client\Minecraft.java
Error:(3918, 13) java: cannot find symbol
  symbol:   class SwapTextureSet
  location: class net.minecraft.client.Minecraft
Warning:(4234, 58) java: non-varargs call of varargs method with inexact argument type for last parameter;
  cast to java.lang.Object for a varargs call
  cast to java.lang.Object[] for a non-varargs call and to suppress this warning
Information:java: C:\minecrift-public-rift\mcp908\src\minecraft\net\minecraft\client\Minecraft.java uses unchecked or unsafe operations.
Information:java: Recompile with -Xlint:unchecked for details.

I..just...wanna...minecrift... Wai :C

**Comment by StellaArtois** [comment]
Ok evidently it needs more work, WIP and all that. I have some time over Xmas to get this up and running properly...

**Comment by Wolfos360** [comment]
I'm so sorry to make it seem like you're being rushed, what with this being the holidays and all that. Runtime 0.7 really did a number on the Rift's library, and Mincraft was one of my favorite experiences with the DK2...  Of course, take your time with this. Your life doesn't revolve around Minecrift after all 
  ^-^

**Comment by Wolfos360** [comment]
The best thing I could think of right now, is have you yourself try running a build and just document your steps. I can mimic that and see if MAYBE its something terribly wrong on my end of things..
