### ISSUE TITLE
crash launch 1.7.10 pre 5

### ISSUE THREAD

**Issue by scribble73** [mabrowning/minecrift#161]
So, I am on mac OS X el capitan V 10.11 but whenever I launch THIS happens :P

any ideas?

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 25/12/15 21:15
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at bao.setupRenderConfiguration(Minecraft.java:3795)
	at bao.ak(Minecraft.java:1328)
	at bao.f(Minecraft.java:1271)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.11
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 110671288 bytes (105 MB) / 167329792 bytes (159 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: minecrift-1.7.10-R1c-nohydra
	LWJGL: 2.9.1
	OpenGL: Intel Iris OpenGL Engine GL version 2.1 INTEL-10.8.77, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by StellaArtois** [comment]
Try using Minecraft 1.7.10 R1c, make sure you have runtime 0.5 installed.

**Comment by StellaArtois** [comment]
‘Minecrift’ 1.7.10 R1c

**Comment by scribble73** [comment]
I do use 1.7.10 R1c, and I even installed the latest java but now it just does this?

---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 26/12/15 18:44
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at bao.setupRenderConfiguration(Minecraft.java:3795)
	at bao.ak(Minecraft.java:1328)
	at bao.f(Minecraft.java:1271)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.11
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 52987376 bytes (50 MB) / 169074688 bytes (161 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: minecrift-1.7.10-R1c-nohydra
	LWJGL: 2.9.1
	OpenGL: Intel Iris OpenGL Engine GL version 2.1 INTEL-10.8.77, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

I found this, maybe it's useful?

[18:44:40 ERROR]: java.io.IOException: Stream closed
[18:44:40 ERROR]: Game ended with bad state (exit code 255)

**Comment by StellaArtois** [comment]
Ok, was looking at the title of the issue. Not sure what's up if your on Oculus 0.5. Maybe somethings been broken by El Capitan.
